apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - redis.yaml
  - flow.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: eib-demo-flow
    includeSelectors: false
