apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - price-feed.yaml
  - trading-engine.yaml
  - dashboard-rbac.yaml
  - dashboard.yaml
  - hft-bot.yaml
  - market-open-cron.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: stock-trading-demo
    includeSelectors: false
