apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - website.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: website-demo
    includeSelectors: false
